spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_data
    username: ${database.user}
    password: ${database.password}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        id:
          new_generator_mappings: false
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: create-drop
    show-sql: true
